<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .link {
            font-size: 42px;
        }
    </style>
</head>

<body>
    <div class="link">
        <a href="http://localhost/magento237/uiexample/index/render">Blog</a>
    </div>
</body>

</html>