<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        /* .product {
            position: relative;
            overflow: hidden;
            padding: 20px;
        }

        .product-category {
            padding: 0 10vw;
            font-size: 30px;
            font-weight: 500;
            margin-bottom: 40px;
            text-transform: capitalize;
        }

        .product-container {
            padding: 0 10vw;
            display: flex;
            overflow-x: auto;
            scroll-behavior: smooth;
        }

        .product-container::-webkit-scrollbar {
            display: none;
        }

        .product-card {
            flex: 0 0 auto;
            width: 250px;
            height: 450px;
            margin-right: 40px;
        }

        .product-image {
            position: relative;
            width: 100%;
            height: 350px;
            overflow: hidden;
        }

        .product-thumb {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .card-btn {
            position: absolute;
            bottom: 10px;
            left: 50%;
            transform: translateX(-50%);
            padding: 10px;
            width: 90%;
            text-transform: capitalize;
            border: none;
            outline: none;
            background: #fff;
            border-radius: 5px;
            transition: 0.5s;
            cursor: pointer;
            opacity: 0;
        }

        .product-card:hover .card-btn {
            opacity: 1;
        }

        .card-btn:hover {
            background: #ff7d7d;
            color: #fff;
        }

        .product-info {
            width: 100%;
            height: 100px;
            padding-top: 5px;
        }

        .product-brand {
            text-transform: uppercase;
        }

        h2.product-brand {
            margin-top: 10px;
            margin-bottom: 10px;
        }

        .product-short-description {
            width: 100%;
            height: 20px;
            line-height: 20px;
            overflow: hidden;
            opacity: 0.5;
            text-transform: capitalize;
            margin: 5px 0;
        }

        .price {
            font-weight: 900;
            font-size: 20px;
        }

        .actual-price {
            margin-left: 20px;
            opacity: 0.5;
            text-decoration: line-through;
        }

        .pre-btn,
        .nxt-btn {
            border: none;
            width: 6vw;
            height: 100%;
            position: absolute;
            top: 0;
            display: flex;
            justify-content: center;
            align-items: center;
            background: linear-gradient(90deg, rgba(255, 255, 255, 0) 0%, #fff 100%);
            cursor: pointer;
            z-index: 2;
        }

        .pre-btn {
            left: 0;
            transform: rotate(180deg);
        }

        .nxt-btn {
            right: 0;
        }

        .pre-btn img,
        .nxt-btn img {
            opacity: 0.2;
        }

        .pre-btn:hover img,
        .nxt-btn:hover img {
            opacity: 1;
        }

        .collection-container {
            width: 100%;
            display: grid;
            grid-template-columns: repeat(2, 1fr);
            grid-gap: 10px;
        }

        .collection {
            position: relative;
        }

        .collection img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .collection p {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            text-align: center;
            color: #fff;
            font-size: 50px;
            text-transform: capitalize;
        }

        .collection:nth-child(3) {
            grid-column: span 2;
            margin-bottom: 10px;
        } */
    </style>
</head>

<body>
    <section class="product">
        <h2 class="product-category">best selling</h2>
        <button class="pre-btn"></button>
        <button class="nxt-btn"></button>
        <div class="product-container">
            <?php
                $categoryId = 2; // this is the category holding your products  
                $categoryProducts = $block->getCategoryProducts($categoryId);
                foreach ($categoryProducts as $product) {
                    $result = [
                        'id'        => $product->getId(),
                        '_sku'      => $product->getSku(),
                        'product_url' => $product->getProductUrl($product),
                        'title'     => $product->getName(),
                        'raw_price' => $product->getFinalPrice()
                        // 'raw_price' => $product->getPrice()
                    ];
            ?>
            <?php
                $productId = $result['id'];
                $imgUrl = $this->getItemImage($productId);
                $elementID = "A".$result['id'];
            ?>
                <div class="product-card">
                    <div class="product-image">
                        <img src="<?= $imgUrl; ?>" alt="" class="product-thumb">
                        <button class="card-btn">add to wishlist</button>
                    </div>
                    <div class="product-info">
                        <h2 class="product-brand" id="<?= $elementID ?>"><?= $result['title'] ?></h2>
                        <p class="product-short-description">a short line about the cloth..</p>
                        <span class="price"><?php
                                                $value =  $result['raw_price'];
                                                $price = "$";
                                                $price .= number_format($value, 2);
                                                echo $price;
                                                ?></span>
                        <span class="actual-price"><?php
                                                $actual_price = $value * 2;
                                                echo "$".$actual_price;
                                                ?></span>
                    </div>
                </div>
            <?php } ?>
        </div>
    </section>
    <script>
        const productContainers = [...document.querySelectorAll('.product-container')];
        const nxtBtn = [...document.querySelectorAll('.nxt-btn')];
        const preBtn = [...document.querySelectorAll('.pre-btn')];

        productContainers.forEach((item, i) => {
            let containerDimensions = item.getBoundingClientRect();
            let containerWidth = containerDimensions.width;

            nxtBtn[i].addEventListener('click', () => {
                item.scrollLeft += containerWidth;
            })

            preBtn[i].addEventListener('click', () => {
                item.scrollLeft -= containerWidth;
            })
        })
    </script>
</body>

</html>