<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .products {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            align-items: center;
            margin: 5px;
            border: 2px solid black;
        }

        .product {
            display: flex;
            flex-direction: column;
            margin: 5px;
            border: 2px solid black;
        }

        .name {
            margin: 10px;
        }

        .price {
            margin: 4px;
        }
    </style>
</head>

<body>
    <div class="container">
        <div id="autoWidth" class="products cs-hidden" >
            <?php
            $categoryId = 2; // this is the category holding your products  
            $categoryProducts = $block->getCategoryProducts($categoryId);
            foreach ($categoryProducts as $product) {
                $result = [
                    'id'        => $product->getId(),
                    '_sku'      => $product->getSku(),
                    'product_url' => $product->getProductUrl($product),
                    'title'     => $product->getName(),
                    'raw_price' => $product->getPrice()
                ];
            ?>
                <?php
                $productId = $result['id'];
                $imgUrl = $this->getItemImage($productId);
                ?>
                <div class="product">
                    <div class="image-box">
                        <img src="<?= $imgUrl; ?>" alt="product-image" />
                    </div>
                    <div class="details">
                        <div class="name">
                            <strong><?= $result['title'] ?></strong>
                        </div>
                        <div class="price">
                            <span class="price"><?php
                                                $value =  $result['raw_price'];
                                                $price = "$";
                                                $price .= number_format($value, 2);
                                                echo $price;
                                                ?></span>
                            <!-- <span class="price"><?= $result['raw_price'] ?></span> -->
                        </div>
                    </div>
                </div>


            <?php } ?>


        </div>
    </div>
    <script>
        // JavaScript Document
        $(document).ready(function() {
            $('#autoWidth').lightSlider({
                autoWidth: true,
                loop: true,
                onSliderLoad: function() {
                    $('#autoWidth').removeClass('cS-hidden');
                }
            });
        });
    </script>
</body>

</html>