<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grid</title>
</head>
<body>
    <div class="grid">
        <table class='table'>
            <thead>
                <tr>
                    <th> ID </th>
                    <th> Title </th>
                    <th> Description </th>
                    <th> Status </th>
                </tr>
            </thead>
            <tbody>
                <?php
                $result = $block->getMessage();
                foreach ($result as $keys => $values) {  ?>
                    <tr>
                        <td><?= $values["blog_id"] ?></td>
                        <td><?= $values["blog_title"] ?></td>
                        <td><?= $values["blog_description"] ?></td>
                        <td><?= $values["status"] ?></td>
                    </tr>
                <?php }  ?>
            </tbody>
        </table>
    </div>
</body>

</html>