<?php if ($block->getQuotes()->getSize()): ?>
    <div class="table-wrapper my-quotes">
        <table class="data table table-quote-items" id="my-quotes-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('My Quotes')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col product"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <th scope="col" class="col comments"><?= $block->escapeHtml(__('Comments')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Actions')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($block->getQuotes() as $quote): ?>
                    <?php $product = $block->getProductById($quote->getProductId()); ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Product Name')) ?>" class="col product">
                            <strong class="product-name">
                                <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>">
                                    <?= $block->escapeHtml($product->getName()) ?>
                                </a>
                            </strong>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?= /* @noEscape */ $block->formatDate($quote->getCreatedAt()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Comments')) ?>" class="col comments">
                            <?= $block->escapeHtml($quote->getComments()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?= $block->escapeHtml($quote->getStatus()) ?>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($quote)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Details')) ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="quote-products-toolbar toolbar bottom">
            <?= $block->getPagerHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty">
        <span><?= $block->escapeHtml(__('You have no quotes.')) ?></span>
    </div>
<?php endif; ?>
<div class="actions-toolbar">
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
            <span><?= $block->escapeHtml(__('Back')) ?></span>
        </a>
    </div>
</div>
