<?php
/** @var \Conceptive\RequestQuote\Block\View $block */
$quote = $block->getQuote();
$product = $block->getProduct();
?>

<?php if ($quote && $product): ?>
    <div class="customer-quote view">
        <div class="quote-details">
            <div class="product-details">
                <div class="product-media">
                <a class="product-photo" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                    <?php if ($block->getHelper()->getProductImageUrl($product)): ?>
                        <img src="<?= $escaper->escapeUrl($block->getHelper()->getProductImageUrl($product)) ?>" 
                             alt="<?= $escaper->escapeHtmlAttr($product->getName()) ?>" />
                    <?php endif; ?>
                </a>
                </div>
                <div class="product-info">
                    <h2 class="product-name"><?= $escaper->escapeHtml($product->getName()) ?></h2>
                    <?php if ($block->getQuote()->getStatus()): ?>
                        <div class="quote-status">
                            <strong><?= $escaper->escapeHtml(__('Status:')) ?></strong>
                            <span><?= $escaper->escapeHtml($quote->getStatus()) ?></span>
                        </div>
                    <?php endif; ?>
                    <?php if ($block->getQuote()->getCreatedAt()): ?>
                        <div class="quote-date">
                            <strong><?= $escaper->escapeHtml(__('Date:')) ?></strong>
                            <span><?= $escaper->escapeHtml($block->formatDate($quote->getCreatedAt())) ?></span>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="quote-comments">
                <strong><?= $escaper->escapeHtml(__('Comments:')) ?></strong>
                <p><?= /* @noEscape */ nl2br($escaper->escapeHtml($quote->getComments())) ?></p>
            </div>
        </div>
    </div>
    
    <div class="actions-toolbar">
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                <span><?= $escaper->escapeHtml(__('Back to My Quotes')) ?></span>
            </a>
        </div>
    </div>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('This quote no longer exists.')) ?></span></div>
<?php endif; ?>
