<?php
$productCollection = $block->getProductCollection();
foreach ($productCollection as $product) { ?>
    <pre>
    <!-- <?php print_r($product->getData()); ?> -->
    </pre>
    <div>
        <a href="<?= $block->escapeUrl($product->getProductUrl()) ?>" class="product photo product-item-photo" tabindex="-1">
            <?= $productImage->toHtml() ?>
        </a>
        <!--
        <img src="<?php echo $product->getData('url_key');  ?>" alt=" No Image">
         <h3><?php echo $product->getData('image');  ?></h3><br>
        <h3><?php echo $product->getData('thumbnail');  ?></h3><br>
        <h3><?php echo $product->getData('small_image');  ?></h3><br> -->
    </div>
<?php
}

?>